name: Build and Release

on:
  push:
    tags:
      - "v*"

env:
  EDGAR_IDENTITY: "Iq De de_iq@iqmo.com"

# Builds on tag
jobs:
  build-and-upload:
    # https://docs.pypi.org/trusted-publishers/using-a-publisher/
    name: Build-Test-Release on Tag
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for tags for dunamai
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: uv sync --group gha --no-dev
      - name: Build package
        run: |
          uv build
      - name: Run tests
        run: |
          uv run pytest --ignore=tests/extras
      - name: Smoke Test Extras - Edgar and HTTP2
        run: |
          uv pip install edgartools h2
          uv run pytest tests/extras/test_edgartools.py tests/extras/test_http2.py
      - name: Upload package to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1