name: Test and Coverage

on:
  workflow_dispatch:

concurrency:
  # cancels superceded runs
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  LATEST_PY_VERSION: &latest '3.13'
  EDGAR_IDENTITY: "Iq De de_iq@iqmo.com"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
        # test oldest & latest versions against ubuntu
        # and one version against windows and macos
        - { os: ubuntu-latest, python-version: *latest }
    environment: test
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies 
        run: uv sync
      # - name: Run tests with coverage and Build
      #   env:
      #     COVERAGE_PROCESS_START: ${{ github.workspace }}/.coveragerc
      #   run: |
      #     uv run pytest --verbose --cov --cov-report=term-missing --ignore=tests/extras
      #     uv build
      # - name: Smoke Test Edgar Tools
      #   if: ${{ matrix.python-version == env.LATEST_PY_VERSION && matrix.os == 'ubuntu-latest' }}
      #   run: |
      #     uv pip install edgartools
      #     uv run pytest tests/extras/test_edgartools.py
      - name: Test Proxy
        if: ${{ matrix.python-version == env.LATEST_PY_VERSION && matrix.os == 'ubuntu-latest' }}
        run: |
          docker run -d --name=tinyproxy -p 6666:8888 monokal/tinyproxy:latest ANY -e ALLOW=0.0.0.0/0
          export HTTP_PROXY = localhost:6666
          export HTTPS_PROXY = localhost:6666
          curl -s -o /dev/null -w "%{http_code}" --proxy $HTTP_PROXY http://httpbin.org/get | grep 200
          curl -s -o /dev/null -w "%{http_code}" --proxy $HTTPS_PROXY https://httpbin.org/get | grep 200
      # - name: Python Coverage Comment if main
      #   if: ${{ github.ref == 'refs/heads/main' && matrix.python-version == env.LATEST_PY_VERSION && matrix.os == 'ubuntu-latest' }}
      #   uses: py-cov-action/python-coverage-comment-action@v3.23
      #   with:
      #     GITHUB_TOKEN: ${{ github.token }}