name: Test and Coverage

on:
  push:
    branches:
      - "*"

env:
  LATEST_PY_VERSION: '3.13'
  EDGAR_IDENTITY: "Iq De de_iq@iqmo.com"

jobs:
  build-and-upload:
    name: ${{ matrix.job_name }} (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_name: Test
        python-version: ["3.9"] # , "3.13", "3.14", "3.14t"
    environment: test
    permissions:
      contents: write
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --all-groups
      - name: Run tests with coverage and Build
        env:
          COVERAGE_PROCESS_START: ${{ github.workspace }}/.coveragerc
        run: |
          uv run pytest --cov --cov-report=term-missing
          uv build
      - name: Python Coverage Comment if main
        if: ${{ github.ref == 'refs/heads/main' && matrix.python-version == env.LATEST_PY_VERSION }}
        uses: py-cov-action/python-coverage-comment-action@v3.23
        with:
          GITHUB_TOKEN: ${{ github.token }}